# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(533, 463)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("YouTube.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.download = QtWidgets.QPushButton(self.centralwidget)
        self.download.setGeometry(QtCore.QRect(190, 330, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.download.setFont(font)
        self.download.setObjectName("download")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 170, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 220, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.link = QtWidgets.QLineEdit(self.centralwidget)
        self.link.setGeometry(QtCore.QRect(130, 170, 291, 20))
        self.link.setObjectName("link")
        self.titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(130, 220, 291, 20))
        self.titulo.setObjectName("titulo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 50, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 40, 171, 101))
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 290, 84, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mp4 = QtWidgets.QRadioButton(self.layoutWidget)
        self.mp4.setObjectName("mp4")
        self.verticalLayout.addWidget(self.mp4)
        self.mp3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.mp3.setObjectName("mp3")
        self.verticalLayout.addWidget(self.mp3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Download"))
        self.download.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "Link"))
        self.label_2.setText(_translate("MainWindow", "Título"))
        self.label_3.setText(_translate("MainWindow", "Download"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/youtube/YouTub-icon.png\"/></p></body></html>"))
        self.mp4.setText(_translate("MainWindow", "Mp4"))
        self.mp3.setText(_translate("MainWindow", "Mp3"))
import Youtube
